### ISSUE TITLE
cec.transmit() doesn't send correct parameters

### ISSUE THREAD

**Issue by David-Strebel-CardinalPeak** [trainman419/python-cec#27]
I'm trying to transmit the cec frame 15:44:44 with the code below. However, the cec frame that I see being sent by my pulse-eight adapter is 15:44:36:35.  Any help on this issue would be appreciated.

destination = 0x5
opcode = 0x44
parameters = bytes(0x41)
cec.transmit(destination, opcode, parameters)

**Comment by nforro** [comment]
The problem is here:

```python
parameters = bytes(0x41)
````

This actually creates `bytes` object of size 0x41 filled with zeroes.

You should use this instead (notice the square brackets):

```python
parameters = bytes([0x41])
```

However, passing such a large `bytes` object to `cec.transmit()` is unexpected and can lead to a crash, so that definitely needs fixing.

**Comment by David-Strebel-CardinalPeak** [comment]
When doing: parameters = bytes([0x44]), I transmit the frame 15:44:5b:36:38:5d. Is there any other method I could to use to send the frame 15:44:44?

**Comment by nforro** [comment]
Where does that come from? A log message? It works fine here on Raspberry Pi:
```
<< 15:44:44
```
You can try to transmit the data using `cec-client`:
```bash
echo "tx 15:44:44" | cec-client -s
```
