### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by kasperdokter** [trainman419/python-cec#37]
The library fails to install. What can I do?

$ pip install cec
Collecting cec
  Using cached https://files.pythonhosted.org/packages/ca/4e/84fae96b6744131a293ec8611dec173a22e06d9f228abc7f0f58f387f9d2/cec-0.2.6.tar.gz
Installing collected packages: cec
  Running setup.py install for cec ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kasper\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kasper\\AppData\\Local\\Temp\\pip-install-hgdgq3nw\\cec\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kasper\\AppData\\Local\\Temp\\pip-install-hgdgq3nw\\cec\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Kasper\AppData\Local\Temp\pip-record-2ixthcny\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Kasper\AppData\Local\Temp\pip-install-hgdgq3nw\cec\
    Complete output (11 lines):
    running install
    running build
    running build_ext
    building 'cec' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude -Ic:\users\kasper\appdata\local\programs\python\python37\include -Ic:\users\kasper\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpcec.cpp /Fobuild\temp.win-amd64-3.7\Release\cec.obj
    cec.cpp
    cec.cpp(32): fatal error C1083: Cannot open include file: 'libcec/cec.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kasper\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kasper\\AppData\\Local\\Temp\\pip-install-hgdgq3nw\\cec\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kasper\\AppData\\Local\\Temp\\pip-install-hgdgq3nw\\cec\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Kasper\AppData\Local\Temp\pip-record-2ixthcny\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by maczet** [comment]
I have the same issue on Raspberry Pi 3 and Python 3.

**Comment by nforro** [comment]
@kasperdokter This is the same issue as #28. I might have a chance to try building cec on Windows, if I succeed, I'll make some sort of HOWTO.

@maczet Unless you run Windows on RPi 3, it's not the same issue.

**Comment by kasperdokter** [comment]
Thanks in advance. It would help me if I can  develop on my Windows machine and run it on the rpi.

**Comment by nforro** [comment]
I've added [Windows installation instructions](https://github.com/trainman419/python-cec#installing-on-windows). Tested with MSVC compiler version 19.22.27905.
Use `pip install git+https://github.com/trainman419/python-cec.git#egg=cec` to pick up the latest commits (for now, until a new version is released on PyPI).

**Comment by trainman419** [comment]
Sorry I've been slow on this; I've uploaded 0.2.7 to pypi.
