### ISSUE TITLE
pip3 install fail Raspbian

### ISSUE THREAD

**Issue by maczet** [trainman419/python-cec#38]
I have problem with installation on Raspbery Pi 3

> pip3 install cec
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cec
  Using cached https://files.pythonhosted.org/packages/ca/4e/84fae96b6744131a293ec8611dec173a22e06d9f228abc7f0f58f387f9d2/cec-0.2.6.tar.gz
Building wheels for collected packages: cec
  Running setup.py bdist_wheel for cec ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-n9uavnwn/cec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-oxwron19 --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'cec' extension
  creating build
  creating build/temp.linux-armv7l-3.7
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iinclude -I/usr/include/python3.7m -c cec.cpp -o build/temp.linux-armv7l-3.7/cec.o
  cec.cpp: In function ?PyObject* set_stream_path(PyObject*, PyObject*)?:
  cec.cpp:487:41: error: invalid conversion from ?const char*? to ?char*? [-fpermissive]
            char * arg_s = PyUnicode_AsUTF8(arg);
                           ~~~~~~~~~~~~~~~~^~~~~
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cec
  Running setup.py clean for cec
Failed to build cec
Installing collected packages: cec
  Running setup.py install for cec ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-n9uavnwn/cec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9gzk5_g6/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_ext
    building 'cec' extension
    creating build
    creating build/temp.linux-armv7l-3.7
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iinclude -I/usr/include/python3.7m -c cec.cpp -o build/temp.linux-armv7l-3.7/cec.o
    cec.cpp: In function ?PyObject* set_stream_path(PyObject*, PyObject*)?:
    cec.cpp:487:41: error: invalid conversion from ?const char*? to ?char*? [-fpermissive]
              char * arg_s = PyUnicode_AsUTF8(arg);
                             ~~~~~~~~~~~~~~~~^~~~~
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-n9uavnwn/cec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9gzk5_g6/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-n9uavnwn/cec/

**Comment by nforro** [comment]
This is already fixed in version **0.2.7**, which hasn't been released on PyPI yet. Use:
```bash
pip install git+https://github.com/trainman419/python-cec.git@0.2.7#egg=cec
```
to install it with pip. See also issue #32.

**Comment by maczet** [comment]
Thanks, this solution resolve my problem.

**Comment by phippodoplis** [comment]
Fixes it for me too. What is the process for getting this in PyPi?

**Comment by trainman419** [comment]
Sorry I've been slow on this; I've uploaded 0.2.7 to pypi.
