### ISSUE TITLE
Getting an invalid signature on  'sudo apt-get update'  while installing on Raspbian

### ISSUE THREAD

**Issue by piningforfjords** [trainman419/python-cec#40]
Err:2 http://packages.namniart.com/repos/pi wheezy InRelease
  The following signatures were invalid: 15A0B3807025FB9CC17EA6FF17BF1CB1D6FC98DF
Reading package lists... Done
W: GPG error: http://packages.namniart.com/repos/pi wheezy InRelease: The following signatures were invalid: 15A0B3807025FB9CC17EA6FF17BF1CB1D6FC98DF
E: The repository 'http://packages.namniart.com/repos/pi wheezy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Any suggestion would be appreciated - Tom

**Comment by trainman419** [comment]
Raspbian now ships with a compatible version of libcec. You should remove the packages.namniart.com/repos/pi repository.

**Comment by piningforfjords** [comment]
That makes sense.  Thanks for the quick response.
