### ISSUE TITLE
UnicodeDecodeError on list_devices

### ISSUE THREAD

**Issue by RomanOnARiver** [trainman419/python-cec#43]
Using Ubuntu 18.04 64-bit the following python3 code suddenly crashes, though it worked fine a few days ago.

```
import cec
cec.init()
cec.list_devices()
```
with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 4: invalid start byte
```
However the same code works on python2, which is getting deprecated.

**Comment by nforro** [comment]
Sorry, I can't reproduce this, but based on the error it seems like you are running it in interactive python interpreter and the invalid byte is actually in your input? I'm not sure about this, but the traceback doesn't make any sense to me otherwise.

**Comment by RomanOnARiver** [comment]
I wanted to say that this issue was resolved by updating the libcec package from [pulses-eight's ppa](https://launchpad.net/~pulse-eight/+archive/ubuntu/libcec) - it's just strange the error started all of a sudden.
