### ISSUE TITLE
How do you know if TV is cec compliant?

### ISSUE THREAD

**Issue by deostroll** [trainman419/python-cec#55]
Not an issue related to the library, but, I thought it pertinent to ask here. The TV is not a very popular brand (westway). But its got two hdmi inputs. And in the TV we have the provision to select which hdmi input we want to watch from.

So if a TV has two hdmi inputs does it mean that probably its not CEC compliant?

The original idea I had in mind was to keep the TV awake via a rpi program. Now the TV does turnoff automatically unless some input from its remote is received. That's where this question actually came from.

**Comment by trainman419** [comment]
I've had TVs with multiple inputs that supported CEC, so I don't think that's a good way to tell if it supports CEC or not.

Instead, I suggest that you check the TV's manual to see if it mentions CEC support. If you have access to a Raspberry Pi, you can also try using the `cec-client` command-line tool from libcec to send commands manually and see if the TV responds to them.

Note that CEC isn't always the same as using a remote, so it might be better to approach your project with an Arduino and an IR LED to build an IR blaster that can send the exact same commands as your existing remote control.

**Comment by deostroll** [comment]
Thanks for the advice. 

Alternatively I tried this with an Amazon firetv stick (which I recently got) which had controls to adjust volume and toggle TV on/off. 

Final result is, they did not work...so tv is not cec compliant I guess.
